// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_app/test/features/payment/services/payment_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_app/features/payment/models/payment_models.dart' as _i2;
import 'package:flutter_app/features/payment/services/backend_api_service.dart'
    as _i4;
import 'package:flutter_app/features/payment/services/local_notification_service.dart'
    as _i9;
import 'package:flutter_app/features/payment/services/local_storage_service.dart'
    as _i7;
import 'package:flutter_app/features/payment/services/subscription_service.dart'
    as _i8;
import 'package:flutter_app/models/order_detail.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOrderResponse_0 extends _i1.SmartFake implements _i2.OrderResponse {
  _FakeOrderResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentStatusResponse_1 extends _i1.SmartFake
    implements _i2.PaymentStatusResponse {
  _FakePaymentStatusResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrderDetail_2 extends _i1.SmartFake implements _i3.OrderDetail {
  _FakeOrderDetail_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BackendApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendApiService extends _i1.Mock implements _i4.BackendApiService {
  MockBackendApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  bool get useMockMode => (super.noSuchMethod(
        Invocation.getter(#useMockMode),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<_i2.OrderResponse> createOrder({
    required int? amount,
    String? reference,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [],
          {
            #amount: amount,
            #reference: reference,
          },
        ),
        returnValue: _i6.Future<_i2.OrderResponse>.value(_FakeOrderResponse_0(
          this,
          Invocation.method(
            #createOrder,
            [],
            {
              #amount: amount,
              #reference: reference,
            },
          ),
        )),
      ) as _i6.Future<_i2.OrderResponse>);

  @override
  _i6.Future<bool> verifyPayment({
    required String? orderId,
    required String? paymentId,
    required String? signature,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPayment,
          [],
          {
            #orderId: orderId,
            #paymentId: paymentId,
            #signature: signature,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i2.PaymentStatusResponse> checkPaymentStatus({
    String? orderId,
    String? paymentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPaymentStatus,
          [],
          {
            #orderId: orderId,
            #paymentId: paymentId,
          },
        ),
        returnValue: _i6.Future<_i2.PaymentStatusResponse>.value(
            _FakePaymentStatusResponse_1(
          this,
          Invocation.method(
            #checkPaymentStatus,
            [],
            {
              #orderId: orderId,
              #paymentId: paymentId,
            },
          ),
        )),
      ) as _i6.Future<_i2.PaymentStatusResponse>);

  @override
  _i6.Future<_i3.OrderDetail> getOrderStatus({required String? orderId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderStatus,
          [],
          {#orderId: orderId},
        ),
        returnValue: _i6.Future<_i3.OrderDetail>.value(_FakeOrderDetail_2(
          this,
          Invocation.method(
            #getOrderStatus,
            [],
            {#orderId: orderId},
          ),
        )),
      ) as _i6.Future<_i3.OrderDetail>);
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i7.LocalStorageService {
  MockLocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveOrder(_i3.OrderDetail? order) => (super.noSuchMethod(
        Invocation.method(
          #saveOrder,
          [order],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.OrderDetail?> getOrder(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #getOrder,
          [orderId],
        ),
        returnValue: _i6.Future<_i3.OrderDetail?>.value(),
      ) as _i6.Future<_i3.OrderDetail?>);

  @override
  _i6.Future<List<_i3.OrderDetail>> getAllOrders() => (super.noSuchMethod(
        Invocation.method(
          #getAllOrders,
          [],
        ),
        returnValue:
            _i6.Future<List<_i3.OrderDetail>>.value(<_i3.OrderDetail>[]),
      ) as _i6.Future<List<_i3.OrderDetail>>);

  @override
  _i6.Future<List<_i3.OrderDetail>> getPendingOrders() => (super.noSuchMethod(
        Invocation.method(
          #getPendingOrders,
          [],
        ),
        returnValue:
            _i6.Future<List<_i3.OrderDetail>>.value(<_i3.OrderDetail>[]),
      ) as _i6.Future<List<_i3.OrderDetail>>);

  @override
  _i6.Future<bool> updateOrder(_i3.OrderDetail? order) => (super.noSuchMethod(
        Invocation.method(
          #updateOrder,
          [order],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> deleteOrder(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #deleteOrder,
          [orderId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [SubscriptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionService extends _i1.Mock
    implements _i8.SubscriptionService {
  MockSubscriptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get activeSubscriptionCount => (super.noSuchMethod(
        Invocation.getter(#activeSubscriptionCount),
        returnValue: 0,
      ) as int);

  @override
  _i6.Future<void> subscribeToOrder(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #subscribeToOrder,
          [orderId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cancelSubscription(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #cancelSubscription,
          [orderId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cancelAllSubscriptions() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllSubscriptions,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocalNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalNotificationService extends _i1.Mock
    implements _i9.LocalNotificationService {
  MockLocalNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAppInForeground => (super.noSuchMethod(
        Invocation.getter(#isAppInForeground),
        returnValue: false,
      ) as bool);

  @override
  set isAppInForeground(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isAppInForeground,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> showPaymentSuccessNotification({
    required String? orderId,
    required int? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showPaymentSuccessNotification,
          [],
          {
            #orderId: orderId,
            #amount: amount,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> showPaymentFailureNotification({
    required String? orderId,
    required int? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showPaymentFailureNotification,
          [],
          {
            #orderId: orderId,
            #amount: amount,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
