// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_app/test/bugfix_preservation/subscription_service_preservation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_app/features/payment/services/local_notification_service.dart'
    as _i5;
import 'package:flutter_app/features/payment/services/local_storage_service.dart'
    as _i2;
import 'package:flutter_app/models/order_detail.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i2.LocalStorageService {
  MockLocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveOrder(_i4.OrderDetail? order) => (super.noSuchMethod(
        Invocation.method(
          #saveOrder,
          [order],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.OrderDetail?> getOrder(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #getOrder,
          [orderId],
        ),
        returnValue: _i3.Future<_i4.OrderDetail?>.value(),
      ) as _i3.Future<_i4.OrderDetail?>);

  @override
  _i3.Future<List<_i4.OrderDetail>> getAllOrders() => (super.noSuchMethod(
        Invocation.method(
          #getAllOrders,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.OrderDetail>>.value(<_i4.OrderDetail>[]),
      ) as _i3.Future<List<_i4.OrderDetail>>);

  @override
  _i3.Future<List<_i4.OrderDetail>> getPendingOrders() => (super.noSuchMethod(
        Invocation.method(
          #getPendingOrders,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.OrderDetail>>.value(<_i4.OrderDetail>[]),
      ) as _i3.Future<List<_i4.OrderDetail>>);

  @override
  _i3.Future<bool> updateOrder(_i4.OrderDetail? order) => (super.noSuchMethod(
        Invocation.method(
          #updateOrder,
          [order],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteOrder(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #deleteOrder,
          [orderId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [LocalNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalNotificationService extends _i1.Mock
    implements _i5.LocalNotificationService {
  MockLocalNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAppInForeground => (super.noSuchMethod(
        Invocation.getter(#isAppInForeground),
        returnValue: false,
      ) as bool);

  @override
  set isAppInForeground(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isAppInForeground,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> showPaymentSuccessNotification({
    required String? orderId,
    required int? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showPaymentSuccessNotification,
          [],
          {
            #orderId: orderId,
            #amount: amount,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> showPaymentFailureNotification({
    required String? orderId,
    required int? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showPaymentFailureNotification,
          [],
          {
            #orderId: orderId,
            #amount: amount,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
