import 'package:razorpay_flutter/razorpay_flutter.dart';

/// Abstract interface for Razorpay SDK to enable dependency injection and testing.
///
/// This interface defines the core methods needed from the Razorpay SDK,
/// allowing us to create mock implementations for testing without requiring
/// real payment processing.
abstract class RazorpayInterface {
  /// Registers an event handler for Razorpay events.
  ///
  /// [event] - Event name (e.g., Razorpay.EVENT_PAYMENT_SUCCESS)
  /// [handler] - Callback function to handle the event
  void on(String event, Function handler);

  /// Opens the Razorpay payment interface with the given options.
  ///
  /// [options] - Map containing payment configuration (key, amount, order_id, etc.)
  void open(Map<String, dynamic> options);

  /// Clears all registered event handlers and releases resources.
  void clear();
}

/// Mock implementation of Razorpay SDK for testing purposes.
///
/// This mock allows tests to:
/// - Track all SDK method calls
/// - Simulate payment success, failure, and wallet events
/// - Verify correct parameters are passed to the SDK
/// - Test payment flows without real payment processing
class MockRazorpay implements RazorpayInterface {
  /// List of all calls made to the open() method with their options.
  /// Used to verify correct parameters are passed to Razorpay SDK.
  final List<Map<String, dynamic>> openCalls = [];

  /// Handler for payment success events.
  Function? successHandler;

  /// Handler for payment error events.
  Function? errorHandler;

  /// Handler for external wallet events.
  Function? walletHandler;

  @override
  void on(String event, Function handler) {
    if (event == Razorpay.EVENT_PAYMENT_SUCCESS) {
      successHandler = handler;
    } else if (event == Razorpay.EVENT_PAYMENT_ERROR) {
      errorHandler = handler;
    } else if (event == Razorpay.EVENT_EXTERNAL_WALLET) {
      walletHandler = handler;
    }
  }

  @override
  void open(Map<String, dynamic> options) {
    // Record the call for verification in tests
    openCalls.add(Map<String, dynamic>.from(options));
  }

  @override
  void clear() {
    openCalls.clear();
    successHandler = null;
    errorHandler = null;
    walletHandler = null;
  }

  // Test helper methods

  /// Simulates a successful payment response from Razorpay SDK.
  ///
  /// [orderId] - The order ID for the payment
  /// [paymentId] - The payment ID generated by Razorpay
  /// [signature] - The signature for payment verification
  void simulateSuccess(String orderId, String paymentId, String signature) {
    if (successHandler != null) {
      successHandler!(PaymentSuccessResponse(orderId, paymentId, signature));
    }
  }

  /// Simulates a payment error response from Razorpay SDK.
  ///
  /// [code] - Error code
  /// [message] - Error message describing what went wrong
  void simulateError(int code, String message) {
    if (errorHandler != null) {
      errorHandler!(PaymentFailureResponse(code, message, null));
    }
  }

  /// Simulates an external wallet selection response from Razorpay SDK.
  ///
  /// [walletName] - Name of the selected wallet (e.g., 'paytm', 'phonepe')
  void simulateWallet(String walletName) {
    if (walletHandler != null) {
      walletHandler!(ExternalWalletResponse(walletName));
    }
  }

  /// Resets all tracked calls and handlers.
  /// Useful for cleaning up between tests.
  void reset() {
    clear();
  }

  /// Returns true if the success handler has been registered.
  bool get hasSuccessHandler => successHandler != null;

  /// Returns true if the error handler has been registered.
  bool get hasErrorHandler => errorHandler != null;

  /// Returns true if the wallet handler has been registered.
  bool get hasWalletHandler => walletHandler != null;

  /// Returns the number of times open() was called.
  int get openCallCount => openCalls.length;

  /// Returns the most recent options passed to open(), or null if never called.
  Map<String, dynamic>? get lastOpenCall =>
      openCalls.isEmpty ? null : openCalls.last;
}
